[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[build.environment]
  NODE_VERSION = "18"
  # Add these Firebase environment variables in Netlify dashboard
  # FIREBASE_API_KEY = "your_api_key"
  # FIREBASE_AUTH_DOMAIN = "your_project.firebaseapp.com"
  # FIREBASE_PROJECT_ID = "your_project_id"
  # FIREBASE_STORAGE_BUCKET = "your_project.appspot.com"
  # FIREBASE_MESSAGING_SENDER_ID = "your_messaging_sender_id"
  # FIREBASE_APP_ID = "your_app_id"
  # FIREBASE_CLIENT_EMAIL = "your_client_email"
  # FIREBASE_PRIVATE_KEY = "your_private_key"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200